"""
=============================================================================
 EDRC AUTO-RUN HELPER  (generated by EDRC_AUTOMATION_SUITE.py - do not edit)
=============================================================================

 Runs ONE suite program completely hands-free:

   1. answers its file-open dialogs from the launcher
   2. clicks its Load TOC / list button, THEN its Load Coordinates button
      (most programs refuse coordinates until the list is loaded)
   3. clicks its Start button
   4. waits for the program to finish (its "running" flag going false)
   5. closes the window so the launcher can start the next program

 The program's own .py file is NOT modified.  This only replaces the
 file-open dialog and hooks the Tk event loop for this one run.

   EDRC_LIST        file handed to the signal / route list dialog
   EDRC_COORDS      file handed to the universal configuration / coordinates dialog
                    (falls back to EDRC_LIST so one combined workbook works)
   EDRC_TRACK_COORDS file handed to Visual Inspection's existing-track-coordinate loader
   EDRC_UNATTENDED  "1" -> auto Load + Start + close (walk-away mode)
                    anything else -> only pre-fill dialogs, you click Start
=============================================================================
"""

import inspect
import os
import sys
import time
import tkinter as tk
import tkinter.filedialog as _fd
import tkinter.messagebox as _mb

# Which functions to drive, per program.  Verified against each source:
#   (load-list button, load-coordinates button, start button)
DRIVERS = {
    "route_initiation.py":          ("load_auto_throw_points", "load_universal_coordinates", "start_automation"),
    "signal_clearance.py":          ("import_master_toc",       "master_load_config",         "start_run"),
    "approach_track_calling_on.py": ("load_excel",              "load_universal_coordinates", "start_run"),
    "lock_route_automation_.py":    ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "auto_throw_of_points.py":      ("load_auto_throw_points",  "load_universal_coordinates", "start_automation"),
    "spl_case_calling_on.py":       ("load_excel",              "load_universal_coordinates", "start_run"),
    "ahead_signal.py":              ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "button_block_testing.py":      ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "emergency_crank_handle.py":    ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "visual_inspection.py":         ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "visual_inspection_track.py":   ("load_lock_routes",        "load_config", "load_existing_track_coordinates", "start_automation"),
    "NEGATIVE_TESTING.py":          ("upload_toc",              "load_universal_coordinates", "start_testing_from_ui"),
    "THROUGH_TESTING.py":           ("upload_toc",              "load_universal_coordinates", "start_testing_from_ui"),
    "NEGATIVE_TESTING_SIGNAL.py":          ("upload_toc",              "load_universal_coordinates", "start_testing_from_ui"),
    "CASCADING.py":                 ("load_cascading_routes",   "load_universal_coordinates", "start_automation"),
    "SEQUENTIAL_ROUTE_RELEASE.py":  ("load_routes",              "load_universal_coordinates", "start_automation"),
    "POINT_LC_CH_SDG_TEST.py":       ("load_excel", "load_universal_coordinates", "start_automation"),
    "EMERGENCY_POINT_KEY_TEST.py":       ("load_excel", "load_universal_coordinates", "start_automation"),
}

RUNNING_FLAG = "running"

_G = {}                     # the program's global namespace (filled below)
_did_autorun = [False]
_RUN_RESULT = [0]   # 0=successful run, 2=automation never started

_UNATTENDED = os.environ.get("EDRC_UNATTENDED") == "1"


def _say(msg):
    print("[EDRC] " + msg, flush=True)


# ---- 1. answer file dialogs from the launcher ---------------------------

_real_open = _fd.askopenfilename


def _auto_open(*a, **k):

    caller = "?"

    try:

        for fr in inspect.stack()[1:6]:
            if fr.function not in ("_auto_open", "<lambda>", "_call"):
                caller = fr.function
                break

        caller_lower = caller.lower()

        # Track capture uses a separate Excel list of track names.  Feed that
        # list directly into Visual Inspection's existing import_track_list()
        # workflow instead of showing a second file picker.
        if "import_track_list" in caller_lower:
            path = os.environ.get("EDRC_TRACK_LIST")
        # Visual Inspection has a separate saved track-coordinate workbook.
        # This check MUST come before the generic "coordinate" check because
        # "load_existing_track_coordinates" also contains "coordinate".
        if "load_existing_track_coordinates" in caller_lower:
            path = os.environ.get("EDRC_TRACK_COORDS")
        elif "coordinate" in caller_lower or "config" in caller_lower:
            path = os.environ.get("EDRC_COORDS") or os.environ.get("EDRC_LIST")
        else:
            path = os.environ.get("EDRC_LIST")

        if path and os.path.exists(path):
            _say("fed  %s  <-  %s" % (caller, os.path.basename(path)))
            return path

    except Exception as exc:
        _say("dialog feed skipped: %s" % exc)

    if _UNATTENDED:
        # A blocking file picker in walk-away mode would wait forever. Return
        # empty (same as the user pressing Cancel) so the program moves on;
        # if it then has nothing to run, start refuses and we close it.
        _say("no file for %s and walk-away is on - skipping the picker" % caller)
        return ""

    return _real_open(*a, **k)


_fd.askopenfilename = _auto_open


# ---- 2. in walk-away mode, never block on a dialog or open Excel ---------

if _UNATTENDED:

    _mb.showinfo = lambda *a, **k: "ok"
    _mb.showwarning = lambda *a, **k: "ok"
    _mb.showerror = lambda *a, **k: "ok"
    _mb.askyesno = lambda *a, **k: True
    _mb.askokcancel = lambda *a, **k: True
    _mb.askquestion = lambda *a, **k: "yes"
    _mb.askretrycancel = lambda *a, **k: False

    # No Excel windows popping open overnight.  Set unconditionally so the
    # program never hits a missing-attribute error on any platform.
    os.startfile = lambda *a, **k: None


# ---- 3. drive the program once its Tk loop starts -----------------------

_key = os.path.basename(sys.argv[1])
_program_key = os.environ.get("EDRC_PROGRAM", "")

# The launcher tells us which buttons to click for this program (by key), so
# a renamed or moved .py still drives.  Fall back to matching by file name.
_env_list = os.environ.get("EDRC_DRIVE_LIST")
_env_coords = os.environ.get("EDRC_DRIVE_COORDS")
_env_config = os.environ.get("EDRC_DRIVE_CONFIG")
_env_track_coords = os.environ.get("EDRC_DRIVE_TRACK_COORDS")
_env_start = os.environ.get("EDRC_DRIVE_START")

if _env_list and _env_config and _env_track_coords and _env_start:
    _profile = (_env_list, _env_config, _env_track_coords, _env_start)
elif _env_list and _env_config and _env_start:
    _profile = (_env_list, _env_config, _env_start)
elif _env_list and _env_coords and _env_start:
    # Backward-compatible profile for the existing programs in Suite 1.
    _profile = (_env_list, _env_coords, _env_start)
else:
    _profile = DRIVERS.get(_key)


def _apply_track_coordinates():
    """Point the child program at the track-coordinate workbook selected
    in the master launcher.  Only used by the 4-step Visual Inspection
    workflow; other programs are unaffected."""
    track_file = os.environ.get("EDRC_TRACK_COORDS")
    if track_file and os.path.exists(track_file):
        _G["COORD_FILE"] = track_file
        _say("track coordinates  <-  %s" % os.path.basename(track_file))
        return True
    return False


def _call(name):

    fn = _G.get(name)

    if callable(fn):
        try:
            _say("click  %s()" % name)
            fn()
            return True
        except Exception as exc:
            _say("%s() error: %s" % (name, exc))
    else:
        _say("button %s not found - skipping" % name)

    return False


def activate_test_panel(timeout=30):
    """Find the already-open railway Test Panel and bring it foreground.

    This deliberately uses the Win32 window-enumeration method from the
    FINAL1 launcher.  The helper itself runs in a separate process, so it
    must not assume that a UIAutomation ``auto`` object exists in the
    launcher namespace.
    """
    _say("TEST PANEL - SEARCHING FOR OPEN WINDOW")
    try:
        import ctypes

        user32 = ctypes.windll.user32
        deadline = time.time() + timeout

        while time.time() < deadline:
            found = []

            @ctypes.WINFUNCTYPE(
                ctypes.c_bool,
                ctypes.c_void_p,
                ctypes.c_void_p,
            )
            def enum_windows(hwnd, _lparam):
                if not user32.IsWindowVisible(hwnd):
                    return True

                length = user32.GetWindowTextLengthW(hwnd)
                if length <= 0:
                    return True

                buf = ctypes.create_unicode_buffer(length + 1)
                user32.GetWindowTextW(hwnd, buf, length + 1)
                title = buf.value.strip()

                if "test panel" in title.lower():
                    found.append(hwnd)
                    return False

                return True

            user32.EnumWindows(enum_windows, 0)

            if found:
                hwnd = found[0]
                _say("TEST PANEL WINDOW FOUND")
                user32.ShowWindow(hwnd, 5)  # SW_SHOW
                user32.SetForegroundWindow(hwnd)
                time.sleep(1.0)
                _say("TEST PANEL ACTIVATED")
                return True

            _say("TEST PANEL NOT FOUND - WAITING...")
            time.sleep(1.0)

        _say("TEST PANEL WINDOW NOT FOUND")
        return False

    except Exception as exc:
        _say("TEST PANEL ERROR: %s" % exc)
        return False

def _begin_autorun(root):

    if _did_autorun[0]:
        return

    _did_autorun[0] = True

    if not _UNATTENDED:
        _say("attended mode - files pre-filled, waiting for you to click Start")
        return

    # ---------------------------------------------------------------
    # TRACK COORDINATE CAPTURE MODE
    # ---------------------------------------------------------------
    # The master console can open Visual Inspection only for the existing
    # track-list -> coordinate-capture workflow.  The actual capture UI is
    # still the one already implemented by visual_inspection_tracks.py.
    if os.environ.get("EDRC_TRACK_CAPTURE") == "1":
        def step_track_list():
            _say("IMPORTING TRACK LIST...")
            if not _call("import_track_list"):
                _say("TRACK LIST IMPORT FUNCTION NOT FOUND")
                return
            root.after(1200, step_track_capture)

        def step_track_capture():
            _say("STARTING TRACK COORDINATE CAPTURE...")
            if not _call("start_track_capture"):
                _say("TRACK CAPTURE FUNCTION NOT FOUND")
                return
            _say("TRACK CAPTURE READY - USE SPACE TO SAVE EACH TRACK")

        root.after(0, step_track_list)
        return

    if not _profile:
        _say("no driver profile for %s - cannot auto-run" % _key)
        if _UNATTENDED:
            _say("walk-away is on - closing in 8s so the queue continues")
            root.after(8000, root.destroy)
        return

    state = {"waited": 0}

    # Visual Inspection uses a dedicated 4-step workflow:
    #   LIST -> CONFIG -> EXISTING TRACK COORDINATES -> START
    # All other Suite 1 programs keep their original 3-step workflow:
    #   LIST -> COORDINATES/CONFIG -> START
    if len(_profile) == 4:
        list_fn, config_fn, track_coords_fn, start_fn = _profile

        def step_list():
            _call(list_fn)
            root.after(900, step_config)

        def step_config():
            _call(config_fn)
            root.after(1500, step_track_coords)

        def step_track_coords():
            _say("LOADING EXISTING TRACK COORDINATES...")
            _apply_track_coordinates()

            # Newer Visual Inspection builds expose a dedicated
            # load_existing_track_coordinates() function.  The current
            # visual_inspection_tracks.py keeps the actual workbook loader
            # as load_track_coordinates(), so use it as a safe fallback.
            if not _call(track_coords_fn):
                _call("load_track_coordinates")

            # Give the dashboard/Test Panel time to finish appearing.
            root.after(1500, step_test_panel)

    else:
        list_fn, coords_fn, start_fn = _profile

        def step_list():
            _call(list_fn)
            root.after(900, step_coords)

        def step_coords():
            _call(coords_fn)
            # The three track-test programs use the external railway
            # Test Panel before their automation starts.  Do this only
            # for those programs; every other Suite 1 workflow keeps its
            # original LIST -> COORDS -> START sequence.
            if _program_key in {"VISUAL_INSPECTION", "VISUAL_INSPECTION_TRACK", "NEGATIVE_TESTING", "BLOCK_TESTING"}:
                root.after(1500, step_test_panel)
            else:
                root.after(900, step_start)

    def step_test_panel():
        _say("CHECKING TEST PANEL...")

        if not activate_test_panel(timeout=30):
            _say("TEST PANEL NOT FOUND")
            _say("AUTOMATION NOT STARTED")
            _RUN_RESULT[0] = 2
            root.after(100, root.destroy)
            return

        _say("TEST PANEL READY")

        # Keep the Test Panel in the foreground before the test begins.
        root.after(1000, step_start)

    def step_start():
        _say("STARTING AUTOMATION...")

        # The Test Panel must be active immediately before the child start
        # routine.  Do not use a second UIAutomation implementation here;
        # activate_test_panel() already performed the Win32 foreground step.
        if _program_key in {"VISUAL_INSPECTION", "VISUAL_INSPECTION_TRACK", "NEGATIVE_TESTING", "BLOCK_TESTING"}:
            if not activate_test_panel(timeout=8):
                _say("TEST PANEL COULD NOT BE ACTIVATED BEFORE START")
                _RUN_RESULT[0] = 2
                root.after(100, root.destroy)
                return
            time.sleep(0.5)

        called = _call(start_fn)
        if not called:
            _say("START FUNCTION COULD NOT BE CALLED")
            _RUN_RESULT[0] = 2
            root.after(100, root.destroy)
            return

        # start_automation() sets the child's global running=True before it
        # starts run_engine().  Give Tk/UIAutomation a short settling period
        # and then observe the real flag.  Do not immediately close the child
        # when it is still false: some programs need a few seconds after the
        # external Test Panel gains focus.
        state["start_waited"] = 0
        root.after(500, check_started)

    def check_started():
        if _G.get(RUNNING_FLAG):
            _RUN_RESULT[0] = 0
            _say("AUTOMATION STARTED - WAITING FOR ENGINE TO FINISH")
            root.after(1500, poll_done)
            return

        state["start_waited"] += 1

        if state["start_waited"] < 20:  # up to 10 seconds
            root.after(500, check_started)
            return

        _say("START AUTOMATION RETURNED WITHOUT RUNNING=TRUE")
        _say("CHILD PROGRAM WAS NOT STARTED - SEE console.log")
        _RUN_RESULT[0] = 2
        root.after(100, root.destroy)

    def poll_done():
        if _G.get(RUNNING_FLAG):
            root.after(1500, poll_done)
            return

        # Do not treat every transition to running=False as success.
        # The track programs set running=False both after a normal completion
        # and after run_engine() catches an automation error.  Inspect the
        # child's own status label so an internal Test Panel/UIAutomation
        # failure is not silently reported as COMPLETED by the master.
        child_status = ""
        try:
            lbl = _G.get("status_label")
            if lbl is not None:
                child_status = str(lbl.cget("text")).strip().upper()
        except Exception:
            child_status = ""

        if child_status in {"ERROR", "FAILED"}:
            _RUN_RESULT[0] = 2
            _say("CHILD AUTOMATION ERROR - NOT REPORTING COMPLETED")
            _say("LEAVING CHILD WINDOW OPEN SO THE REAL ERROR IS VISIBLE")
            return

        _RUN_RESULT[0] = 0
        _say("AUTOMATION FINISHED - closing child window")
        root.after(1500, root.destroy)

    root.after(0, step_list)


_real_mainloop = tk.Misc.mainloop


def _patched_mainloop(self, *a, **k):

    if not _did_autorun[0]:
        self.after(1400, lambda: _begin_autorun(self))

    return _real_mainloop(self, *a, **k)


tk.Misc.mainloop = _patched_mainloop


# ---- run the program in a namespace we can read -------------------------

if __name__ == "__main__":

    target = sys.argv[1]
    sys.argv = [target] + sys.argv[2:]

    _G = {"__name__": "__main__", "__file__": target}

    _say("HELPER BOOTED")
    _say("TARGET SCRIPT: %s" % target)
    _say("PYTHON: %s" % sys.executable)
    _say("WORKING DIRECTORY: %s" % os.getcwd())
    _say("PROGRAM KEY: %s | UNATTENDED: %s" % (_program_key, _UNATTENDED))
    _say("DRIVER PROFILE: %s" % (str(_profile),))
    try:
        with open(target, "r", encoding="utf-8") as _fh:
            _code = compile(_fh.read(), target, "exec")
        _say("BACKEND SOURCE READ; EXECUTING BACKEND")
        exec(_code, _G)
        _say("BACKEND MAINLOOP EXITED")
    except BaseException as exc:
        import traceback
        _say("FATAL BACKEND STARTUP ERROR: %s: %s" % (type(exc).__name__, exc))
        traceback.print_exc()
        raise

    # Tell the master whether the requested automation actually started.
    # This prevents an early child exit from being displayed as COMPLETED.
    sys.exit(_RUN_RESULT[0])
