r"""
=============================================================================
 EDRC RAILWAY SIGNAL AUTOMATION SUITE  -  MASTER CONSOLE
=============================================================================

 A single front end for every test program in the suite.

 FLOW
 ----
   STEP 1  OEM            ->  HITACHI / SIEMENS / MEDHA / NIPPON /
                              KYOSAN / HIMA
   STEP 2  DATA           ->  UPLOAD TOC, LOAD COORDINATES (NEW / EXISTING),
                              LOAD TRACK EXCEL, LOCK ROUTE, SPL CASE,
                              AUTO THROW POINTS
   STEP 3  PROGRAMS       ->  Tick the programs to run. The tick ORDER is the
                              RUN ORDER (a numbered badge shows the position).
   STEP 4  EXECUTION      ->  Programs run ONE AFTER ANOTHER. Each program
                              finishes and its report is collected into the
                              session folder BEFORE the next one launches.

 REPORTS
 -------
   EDRC_REPORTS\<OEM>\SESSION_<yyyymmdd_hhmmss>\
        01_ROUTE_INITIATION\...xlsx
        02_SIGNAL_CLEARANCE\...xlsx
        SESSION.json          (OEM, data files, run order, results)

 NOTE
 ----
   The individual test programs are NOT modified by this launcher. Each one
   is started as its own process with its own window, exactly as if it were
   opened from PyCharm. The launcher waits for that window to close, picks
   up the Excel report it wrote, then starts the next program.

   The chosen data files are also published to the child process through
   environment variables (EDRC_TOC, EDRC_COORDS, ...) and SESSION.json, so
   the test programs can auto-load them later if you decide to add that.

 Author : EDRC Team
=============================================================================
"""

import json
import os
import queue
import shutil
import subprocess
import sys
import threading
import time
from datetime import datetime
from pathlib import Path

import tkinter as tk
from tkinter import filedialog, messagebox

try:
    from PIL import Image, ImageTk
    PIL_OK = True
except Exception:
    PIL_OK = False


# =============================================================================
# =============================================================================
#  CONFIGURATION
# =============================================================================
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent

# Folder that holds the individual test programs.
SCRIPT_DIR = BASE_DIR

# Where session reports are archived.
REPORTS_ROOT = BASE_DIR / "EDRC_REPORTS"

# Remembers any script paths you located manually.
SUITE_CONFIG = BASE_DIR / "EDRC_SUITE_CONFIG.json"

# Logos (text fallback if missing).
IR_LOGO = BASE_DIR / "indian_railways.png"
COMPANY_LOGO = BASE_DIR / "company_logo.png"

# Universal Yard Coordinate Recorder - used by LOAD COORDINATES > NEW.
RECORDER_CANDIDATES = [
    "universal_yard_coordinate_recorder.py",
    "yard_coordinate_recorder.py",
    "coordinate_recorder.py",
    "universal_yard_coordinates_recorder.py",
]

# Small helper written next to this launcher.  It runs a program with its
# file-open dialogs pre-filled from the launcher, WITHOUT editing the
# program's own source - see AUTOFEED_SOURCE below.
AUTOFEED_HELPER = BASE_DIR / "_edrc_autofeed.py"

AUTOFEED_SOURCE = r'''"""
=============================================================================
 EDRC AUTO-RUN HELPER  (generated by EDRC_AUTOMATION_SUITE.py - do not edit)
=============================================================================

 Runs ONE suite program completely hands-free:

   1. answers its file-open dialogs from the launcher
   2. clicks its Load TOC / list button, THEN its Load Coordinates button
      (most programs refuse coordinates until the list is loaded)
   3. clicks its Start button
   4. waits for the program to finish (its "running" flag going false)
   5. closes the window so the launcher can start the next program

 The program's own .py file is NOT modified.  This only replaces the
 file-open dialog and hooks the Tk event loop for this one run.

   EDRC_LIST        file handed to the signal / route list dialog
   EDRC_COORDS      file handed to the coordinates dialog
                    (falls back to EDRC_LIST so one combined workbook works)
   EDRC_UNATTENDED  "1" -> auto Load + Start + close (walk-away mode)
                    anything else -> only pre-fill dialogs, you click Start
=============================================================================
"""

import inspect
import os
import sys
import time
import tkinter as tk
import tkinter.filedialog as _fd
import tkinter.messagebox as _mb

# Which functions to drive, per program.  Verified against each source:
#   (load-list button, load-coordinates button, start button)
DRIVERS = {
    "route_initiation.py":          ("load_auto_throw_points", "load_universal_coordinates", "start_automation"),
    "signal_clearance.py":          ("import_master_toc",       "master_load_config",         "start_run"),
    "approach_track_calling_on.py": ("load_excel",              "load_universal_coordinates", "start_run"),
    "lock_route_automation_.py":    ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "auto_throw_of_points.py":      ("load_auto_throw_points",  "load_universal_coordinates", "start_automation"),
    "spl_case_calling_on.py":       ("load_excel",              "load_universal_coordinates", "start_run"),
    "ahead_signal.py":              ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "button_block_testing.py":      ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "emergency_crank_handle.py":    ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "visual_inspection.py":         ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "NEGATIVE_TESTING.py":          ("upload_toc",              "load_universal_coordinates", "start_testing_from_ui"),
    "THROUGH_TESTING.py":           ("upload_toc",              "load_universal_coordinates", "start_testing_from_ui"),
    "CASCADING.py":                 ("load_cascading_routes",   "load_universal_coordinates", "start_automation"),
    "SEQUENTIAL_ROUTE_RELEASE.py":  ("load_routes",              "load_universal_coordinates", "start_automation"),
}

RUNNING_FLAG = "running"

_G = {}                     # the program's global namespace (filled below)
_did_autorun = [False]

_UNATTENDED = os.environ.get("EDRC_UNATTENDED") == "1"


def _say(msg):
    print("[EDRC] " + msg, flush=True)


# ---- 1. answer file dialogs from the launcher ---------------------------

_real_open = _fd.askopenfilename


def _auto_open(*a, **k):

    caller = "?"

    try:

        for fr in inspect.stack()[1:6]:
            if fr.function not in ("_auto_open", "<lambda>", "_call"):
                caller = fr.function
                break

        if "coordinate" in caller.lower():
            path = os.environ.get("EDRC_COORDS") or os.environ.get("EDRC_LIST")
        else:
            path = os.environ.get("EDRC_LIST")

        if path and os.path.exists(path):
            _say("fed  %s  <-  %s" % (caller, os.path.basename(path)))
            return path

    except Exception as exc:
        _say("dialog feed skipped: %s" % exc)

    if _UNATTENDED:
        # A blocking file picker in walk-away mode would wait forever. Return
        # empty (same as the user pressing Cancel) so the program moves on;
        # if it then has nothing to run, start refuses and we close it.
        _say("no file for %s and walk-away is on - skipping the picker" % caller)
        return ""

    return _real_open(*a, **k)


_fd.askopenfilename = _auto_open


# ---- 2. in walk-away mode, never block on a dialog or open Excel ---------

if _UNATTENDED:

    _mb.showinfo = lambda *a, **k: "ok"
    _mb.showwarning = lambda *a, **k: "ok"
    _mb.showerror = lambda *a, **k: "ok"
    _mb.askyesno = lambda *a, **k: True
    _mb.askokcancel = lambda *a, **k: True
    _mb.askquestion = lambda *a, **k: "yes"
    _mb.askretrycancel = lambda *a, **k: False

    # No Excel windows popping open overnight.  Set unconditionally so the
    # program never hits a missing-attribute error on any platform.
    os.startfile = lambda *a, **k: None


# ---- 3. drive the program once its Tk loop starts -----------------------

_key = os.path.basename(sys.argv[1])

# The launcher tells us which buttons to click for this program (by key), so
# a renamed or moved .py still drives.  Fall back to matching by file name.
_env_list = os.environ.get("EDRC_DRIVE_LIST")
_env_coords = os.environ.get("EDRC_DRIVE_COORDS")
_env_start = os.environ.get("EDRC_DRIVE_START")

if _env_list and _env_coords and _env_start:
    _profile = (_env_list, _env_coords, _env_start)
else:
    _profile = DRIVERS.get(_key)


def _call(name):

    fn = _G.get(name)

    if callable(fn):
        try:
            _say("click  %s()" % name)
            fn()
            return True
        except Exception as exc:
            _say("%s() error: %s" % (name, exc))
    else:
        _say("button %s not found - skipping" % name)

    return False


def _begin_autorun(root):

    if _did_autorun[0]:
        return

    _did_autorun[0] = True

    if not _UNATTENDED:
        _say("attended mode - files pre-filled, waiting for you to click Start")
        return

    if not _profile:
        _say("no driver profile for %s - cannot auto-run" % _key)
        if _UNATTENDED:
            _say("walk-away is on - closing in 8s so the queue continues")
            root.after(8000, root.destroy)
        return

    list_fn, coords_fn, start_fn = _profile
    state = {"waited": 0}

    # IMPORTANT: load the LIST (TOC / RCC / etc.) FIRST, then coordinates.
    # Four of the programs refuse to load coordinates until their list is in
    # ("Please load ... first"), so coordinates-first silently loads nothing.
    def step_list():
        _call(list_fn)
        root.after(900, step_coords)

    def step_coords():
        _call(coords_fn)
        root.after(900, step_start)

    def step_start():
        _call(start_fn)
        root.after(600, check_started)

    def check_started():
        if _G.get(RUNNING_FLAG):
            _say("started - waiting for it to finish")
            root.after(1500, poll_done)
        else:
            state["waited"] += 1
            if state["waited"] * 500 >= 6000:
                _say("did not start within 6s (data not loaded?) - closing")
                root.after(300, root.destroy)
            else:
                root.after(500, check_started)

    def poll_done():
        if not _G.get(RUNNING_FLAG):
            _say("finished - closing window")
            root.after(1500, root.destroy)
        else:
            root.after(1500, poll_done)

    root.after(0, step_list)


_real_mainloop = tk.Misc.mainloop


def _patched_mainloop(self, *a, **k):

    if not _did_autorun[0]:
        self.after(1400, lambda: _begin_autorun(self))

    return _real_mainloop(self, *a, **k)


tk.Misc.mainloop = _patched_mainloop


# ---- run the program in a namespace we can read -------------------------

if __name__ == "__main__":

    target = sys.argv[1]
    sys.argv = [target] + sys.argv[2:]

    _G = {"__name__": "__main__", "__file__": target}

    with open(target, "r", encoding="utf-8") as _fh:
        _code = compile(_fh.read(), target, "exec")

    exec(_code, _G)
'''


# ---------------------------------------------------------------- OEM LIST ---

OEMS = [
    {"code": "HITACHI", "note": "Hitachi Rail STS",        "accent": "#E1443B"},
    {"code": "SIEMENS", "note": "Siemens Mobility",        "accent": "#00A0A0"},
    {"code": "MEDHA",   "note": "Medha Servo Drives",      "accent": "#F2B23A"},
    {"code": "NIPPON",  "note": "Nippon Signal",           "accent": "#4C7DF0"},
    {"code": "KYOSAN",  "note": "Kyosan Electric",         "accent": "#22A45D"},
    {"code": "HIMA",    "note": "HIMA Paul Hildebrandt",   "accent": "#9A6BEF"},
]


# --------------------------------------------------------------- DATA SLOTS ---
# The reality of the test programs:
#
#   * Every program reads its signal / route LIST from the sheet named TOC,
#     EXCEPT spl_case_calling_on which reads the sheet SPL_CASE_CALLING_ON.
#   * Every program also loads the universal COORDINATES workbook
#     (MAIN / SHUNT / CAL / POINT / CH / LC sheets).
#
# So there are only three inputs, not one per program:
#
#   TOC        - one master workbook, shared by every program except SPL case
#   COORDS     - the universal yard coordinates, shared by every program
#   SPL_CASE   - a separate workbook, used ONLY by SPL CASE CALLING ON
#
# key      : internal name + environment variable suffix
# label    : button caption
# hint     : one line telling the user what the file is
# recorder : True  -> shows the NEW / EXISTING pair
# core     : True  -> counted in the "ready" indicator on step 2
# role     : "list"  file is fed to a program's signal/route dialog
#            "coords" file is fed to a program's coordinates dialog

DATA_SLOTS = [
    {
        "key": "TOC",
        "label": "UPLOAD TOC",
        "hint": "Master workbook  -  sheet TOC.  Used by EVERY program "
                "except SPL CASE CALLING ON.",
        "recorder": False,
        "core": True,
        "role": "list",
    },
    {
        "key": "COORDS",
        "label": "LOAD COORDINATES",
        "hint": "Universal yard coordinates  (MAIN / SHUNT / CAL / POINT / "
                "CH / LC).  If these sheets already live inside the TOC "
                "workbook, you can skip this.",
        "recorder": True,
        "core": False,
        "role": "coords",
    },
    {
        "key": "SPL_CASE",
        "label": "UPLOAD SPL CASE INPUT",
        "hint": "Separate workbook  -  sheet SPL_CASE_CALLING_ON.  Used ONLY "
                "by SPL CASE CALLING ON.",
        "recorder": False,
        "core": False,
        "role": "list",
    },
]


# ----------------------------------------------------------------- PROGRAMS ---
# script   : file name inside SCRIPT_DIR
# reports  : file-name prefixes the program writes (used to collect the report)
# needs    : DATA_SLOTS keys the program expects

PROGRAMS = [
    {
        "key": "ROUTE_INITIATION",
        "name": "ROUTE INITIATION",
        "desc": "Verifies the route initiation indication for every signal route.",
        "script": "route_initiation.py",
        "reports": ["Route_Intiation", "Route_Initiation", "ROUTE_INITIATION"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "SIGNAL_CLEARANCE",
        "name": "SIGNAL CLEARANCE",
        "desc": "Main, calling-on and shunt clearance in one pass.  MAIN -> its "
                "CALLING-ON per signal, then all SHUNT signals.",
        "script": "signal_clearance.py",
        "reports": ["Signal_Clearance_Report"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "SPL_CASE_CALLING_ON",
        "name": "SPL CASE CALLING ON",
        "desc": "Special case calling-on.  Main route set first, then the "
                "calling-on aspect is verified row by row.  This is the ONLY "
                "program that takes its own separate input file.",
        "script": "spl_case_calling_on.py",
        "reports": ["Calling_On_Report"],
        "needs": ["SPL_CASE", "COORDS"],
    },
    {
        "key": "APPROACH_TRACK_CALLING_ON",
        "name": "APPROACH TRACK CALLING ON",
        "desc": "Drops the approach track and checks the calling-on signal "
                "clears only with the track occupied.",
        "script": "approach_track_calling_on.py",
        "reports": ["APPROACH_TRACK_CALLING_On_Report", "APPROACH_TRACK"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "LOCK_ROUTE",
        "name": "LOCK ROUTE AUTOMATION",
        "desc": "Sets a main signal route and confirms every associated route "
                "locks as per the interlocking.",
        "script": "lock_route_automation_.py",
        "reports": ["LOCK_ROUTE_REPORT"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "AUTO_THROW_POINTS",
        "name": "AUTO THROW OF POINTS",
        "desc": "Confirms points throw automatically to the correct position "
                "when the route is initiated.",
        "script": "auto_throw_of_points.py",
        "reports": ["AUTO_THROW_OF_POINTS"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "AHEAD_SIGNAL",
        "name": "AHEAD SIGNAL",
        "desc": "Tests the red aspect of the route signal and the associated "
                "ahead signal.",
        "script": "ahead_signal.py",
        "reports": ["AHEAD_SIGNAL", "Ahead_Signal"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "BUTTON_BLOCK",
        "name": "BUTTON BLOCK",
        "desc": "Tests button block operation for configured signal routes.",
        "script": "button_block_testing.py",
        "reports": ["BUTTON BLOCK REPORT", "BUTTON_BLOCK"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "EMERGENCY_CRANK_HANDLE",
        "name": "EMERGENCY CRANK HANDLE",
        "desc": "Tests emergency crank handle operation for configured signal "
                "routes.",
        "script": "emergency_crank_handle.py",
        "reports": ["Signal_Clearance_Report", "EMERGENCY_CRANK"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "VISUAL_INSPECTION",
        "name": "VISUAL INSPECTION",
        "desc": "Performs visual inspection of the configured signalling "
                "equipment.",
        "script": "visual_inspection.py",
        "reports": ["VISUAL_INSPECTION"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "NEGATIVE_TESTING",
        "name": "NEGATIVE TESTING",
        "desc": "Verifies signal, point, and crank handle relay bits are "
                "correctly deactivated when a route is not established.",
        "script": "NEGATIVE_TESTING.py",
        "reports": ["NEGATIVE_TESTING"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "THROUGH_TESTING",
        "name": "THROUGH TESTING",
        "desc": "Verifies a train can pass through a sequence of signals "
                "and routes end to end.",
        "script": "THROUGH_TESTING.py",
        "reports": ["THROUGH_TESTING"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "CASCADING",
        "name": "CASCADING",
        "desc": "Verifies that setting a main route correctly cascades "
                "control bits to the associated signals and points.",
        "script": "CASCADING.py",
        "reports": ["CASCADING"],
        "needs": ["TOC", "COORDS"],
    },
    {
        "key": "SEQUENTIAL_ROUTE_RELEASE",
        "name": "SEQUENTIAL ROUTE RELEASE",
        "desc": "Verifies routes release in the correct sequence as track "
                "sections and control bits are restored.",
        "script": "SEQUENTIAL_ROUTE_RELEASE.py",
        "reports": ["SEQUENTIAL_ROUTE_RELEASE"],
        "needs": ["TOC", "COORDS"],
    },
]

PROGRAM_BY_KEY = {p["key"]: p for p in PROGRAMS}


# Which functions the helper should click to drive each program, keyed by the
# PROGRAM (not the file name).  The launcher always knows which program a row
# is, so it passes this to the helper directly - a renamed or moved .py still
# drives correctly.  Order used at run time: LIST first, then COORDS, then
# START.  Tuple = (load_list_fn, load_coords_fn, start_fn).
PROGRAM_DRIVERS = {
    "ROUTE_INITIATION":          ("load_auto_throw_points", "load_universal_coordinates", "start_automation"),
    "SIGNAL_CLEARANCE":          ("import_master_toc",       "master_load_config",         "start_run"),
    "APPROACH_TRACK_CALLING_ON": ("load_excel",              "load_universal_coordinates", "start_run"),
    "LOCK_ROUTE":                ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "AUTO_THROW_POINTS":         ("load_auto_throw_points",  "load_universal_coordinates", "start_automation"),
    "SPL_CASE_CALLING_ON":       ("load_excel",              "load_universal_coordinates", "start_run"),
    "AHEAD_SIGNAL":              ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "BUTTON_BLOCK":              ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "EMERGENCY_CRANK_HANDLE":    ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "VISUAL_INSPECTION":         ("load_lock_routes",        "load_universal_coordinates", "start_automation"),
    "NEGATIVE_TESTING":          ("upload_toc",              "load_universal_coordinates", "start_testing_from_ui"),
    "THROUGH_TESTING":           ("upload_toc",              "load_universal_coordinates", "start_testing_from_ui"),
    "CASCADING":                 ("load_cascading_routes",   "load_universal_coordinates", "start_automation"),
    "SEQUENTIAL_ROUTE_RELEASE":  ("load_routes",              "load_universal_coordinates", "start_automation"),
}


# =============================================================================
# =============================================================================
#  THEME
# =============================================================================
# =============================================================================

class T:
    """Design tokens.  The palette is built from signal aspects - red, amber
    and green are never decorative here, they always carry state."""

    INK = "#0B1220"        # header / mast
    PANEL = "#131C2E"      # raised dark panel
    PANEL_2 = "#1B2740"    # dark panel hover
    BG = "#EEF1F6"         # page background
    CARD = "#FFFFFF"
    CARD_EDGE = "#D5DCE7"
    CARD_EDGE_HOT = "#2F6BFF"

    TEXT = "#0B1220"
    TEXT_SOFT = "#5A6B85"
    TEXT_INV = "#FFFFFF"
    TEXT_MUTE = "#8FA0BC"

    BLUE = "#2F6BFF"
    BLUE_HOT = "#1B54E0"
    VIOLET = "#7C4DEF"
    VIOLET_HOT = "#6A3BDD"

    RED = "#E1443B"        # aspect RED  - stopped / failed
    AMBER = "#F2B23A"      # aspect AMBER - running / waiting
    GREEN = "#22A45D"      # aspect GREEN - complete / ready
    GREY = "#7C8AA0"       # lamp off

    SLATE = "#334155"

    @staticmethod
    def f(size, weight="normal"):
        return ("Segoe UI", size, weight)

    @staticmethod
    def mono(size, weight="normal"):
        return ("Consolas", size, weight)


# =============================================================================
# =============================================================================
#  CUSTOM WIDGETS
# =============================================================================
# =============================================================================

def rounded(canvas, x1, y1, x2, y2, r, **kw):
    """Draws a rounded rectangle as a smoothed polygon."""

    r = min(r, abs(x2 - x1) / 2, abs(y2 - y1) / 2)

    pts = [
        x1 + r, y1, x2 - r, y1, x2, y1, x2, y1 + r,
        x2, y2 - r, x2, y2, x2 - r, y2, x1 + r, y2,
        x1, y2, x1, y2 - r, x1, y1 + r, x1, y1,
    ]

    return canvas.create_polygon(pts, smooth=True, **kw)


class RButton(tk.Canvas):
    """Flat rounded button with a hover state.  Pure tkinter, no images."""

    def __init__(self, parent, text, command=None, w=230, h=46,
                 face=T.BLUE, face_hot=None, fg=T.TEXT_INV,
                 font=None, radius=10, edge="", bg=None):

        bg = bg if bg is not None else _bg_of(parent)

        super().__init__(parent, width=w, height=h, bg=bg,
                         highlightthickness=0, bd=0)

        self.command = command
        self.face = face
        self.face_hot = face_hot or _shade(face, -0.14)
        self.enabled = True

        # NOTE: never store width as self._w - tkinter uses that attribute
        # internally for the widget path name.
        self.btn_w, self.btn_h = w, h

        self.shape = rounded(self, 1, 1, w - 1, h - 1, radius,
                             fill=face, outline=edge or face)

        self.label = self.create_text(w / 2, h / 2, text=text, fill=fg,
                                      font=font or T.f(11, "bold"))

        self.configure(cursor="hand2")

        self.bind("<Enter>", self._enter)
        self.bind("<Leave>", self._leave)
        self.bind("<Button-1>", self._press)
        self.bind("<ButtonRelease-1>", self._release)

    # -- state -------------------------------------------------------------

    def set_text(self, text):
        self.itemconfig(self.label, text=text)

    def set_face(self, face):
        self.face = face
        self.face_hot = _shade(face, -0.14)
        self.itemconfig(self.shape, fill=face, outline=face)

    def set_enabled(self, flag):
        self.enabled = flag
        if flag:
            self.itemconfig(self.shape, fill=self.face, outline=self.face)
            self.itemconfig(self.label, fill=T.TEXT_INV)
            self.configure(cursor="hand2")
        else:
            self.itemconfig(self.shape, fill="#C3CBD8", outline="#C3CBD8")
            self.itemconfig(self.label, fill="#EFF2F7")
            self.configure(cursor="arrow")

    # -- events ------------------------------------------------------------

    def _enter(self, _=None):
        if self.enabled:
            self.itemconfig(self.shape, fill=self.face_hot,
                            outline=self.face_hot)

    def _leave(self, _=None):
        if self.enabled:
            self.itemconfig(self.shape, fill=self.face, outline=self.face)

    def _press(self, _=None):
        if self.enabled:
            self.move(self.label, 0, 1)

    def _release(self, _=None):
        if not self.enabled:
            return
        self.move(self.label, 0, -1)
        if self.command:
            self.command()


class GhostButton(RButton):
    """Outlined button for secondary actions such as BACK."""

    def __init__(self, parent, text, command=None, w=150, h=46,
                 colour=T.SLATE, **kw):

        bg = _bg_of(parent)

        super().__init__(parent, text, command, w=w, h=h,
                         face=bg, fg=colour, edge=colour, bg=bg, **kw)

        self.itemconfig(self.shape, fill=bg, outline=colour, width=1)
        self.base_bg = bg
        self.colour = colour

    def _enter(self, _=None):
        if self.enabled:
            self.itemconfig(self.shape, fill="#E2E8F1", outline=self.colour)

    def _leave(self, _=None):
        if self.enabled:
            self.itemconfig(self.shape, fill=self.base_bg,
                            outline=self.colour)


class Lamp(tk.Canvas):
    """A signal aspect lamp.  Used for step progress and program status."""

    def __init__(self, parent, d=16, colour=T.GREY, bg=None, glow=True):

        bg = bg if bg is not None else _bg_of(parent)
        pad = 4 if glow else 1
        size = d + pad * 2

        super().__init__(parent, width=size, height=size, bg=bg,
                         highlightthickness=0, bd=0)

        self.glow_id = self.create_oval(1, 1, size - 1, size - 1,
                                        fill=bg, outline=bg) if glow else None

        self.bulb = self.create_oval(pad, pad, pad + d, pad + d,
                                     fill=colour, outline=_shade(colour, -0.2))

        self.bg = bg
        self.set(colour)

    def set(self, colour, lit=True):
        self.itemconfig(self.bulb, fill=colour,
                        outline=_shade(colour, -0.25))
        if self.glow_id is not None:
            halo = _mix(colour, self.bg, 0.72) if lit else self.bg
            self.itemconfig(self.glow_id, fill=halo, outline=halo)


class Toggle(tk.Canvas):
    """A compact on/off pill switch."""

    def __init__(self, parent, value=True, command=None, bg=None):

        bg = bg if bg is not None else _bg_of(parent)
        self.w, self.h = 52, 26

        super().__init__(parent, width=self.w, height=self.h, bg=bg,
                         highlightthickness=0, bd=0)

        self.value = value
        self.command = command

        self.track = rounded(self, 1, 1, self.w - 1, self.h - 1, 12,
                             fill=T.GREEN, outline=T.GREEN)

        self.knob = self.create_oval(0, 0, 0, 0, fill="white",
                                    outline="#E2E8F1")

        self.configure(cursor="hand2")
        self.bind("<Button-1>", self._flip)

        self._draw()

    def _draw(self):

        if self.value:
            self.itemconfig(self.track, fill=T.GREEN, outline=T.GREEN)
            x = self.w - self.h + 3
        else:
            self.itemconfig(self.track, fill="#B9C4D4", outline="#B9C4D4")
            x = 3

        self.coords(self.knob, x, 3, x + self.h - 6, self.h - 3)

    def _flip(self, _=None):
        self.value = not self.value
        self._draw()
        if self.command:
            self.command(self.value)

    def set(self, value):
        self.value = value
        self._draw()


class CheckMark(tk.Canvas):
    """Square tick box with an order badge for the run sequence."""

    SIZE = 30

    def __init__(self, parent, bg=None):

        bg = bg if bg is not None else _bg_of(parent)
        s = self.SIZE

        super().__init__(parent, width=s, height=s, bg=bg,
                         highlightthickness=0, bd=0)

        self.box = rounded(self, 2, 2, s - 2, s - 2, 8,
                           fill="#FFFFFF", outline="#B9C4D4")

        self.tick = self.create_text(s / 2, s / 2 - 1, text="",
                                     fill=T.TEXT_INV, font=T.f(12, "bold"))

    def set(self, checked, order=None):
        if checked:
            self.itemconfig(self.box, fill=T.BLUE, outline=T.BLUE)
            self.itemconfig(self.tick, text=str(order) if order else "OK")
        else:
            self.itemconfig(self.box, fill="#FFFFFF", outline="#B9C4D4")
            self.itemconfig(self.tick, text="")


# --------------------------------------------------------------- helpers -----

def _bg_of(widget):
    try:
        return widget.cget("bg")
    except Exception:
        return T.BG


def _hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _rgb_to_hex(rgb):
    return "#%02x%02x%02x" % tuple(max(0, min(255, int(c))) for c in rgb)


def _shade(colour, amount):
    """amount < 0 darkens, amount > 0 lightens."""

    r, g, b = _hex_to_rgb(colour)

    if amount < 0:
        f = 1 + amount
        return _rgb_to_hex((r * f, g * f, b * f))

    return _rgb_to_hex((r + (255 - r) * amount,
                        g + (255 - g) * amount,
                        b + (255 - b) * amount))


def _mix(a, b, t):
    """t = 0 -> a,  t = 1 -> b"""

    ra, ga, ba = _hex_to_rgb(a)
    rb, gb, bb = _hex_to_rgb(b)

    return _rgb_to_hex((ra + (rb - ra) * t,
                        ga + (gb - ga) * t,
                        ba + (bb - ba) * t))


def card(parent, **kw):
    """A white panel with a hairline border."""

    return tk.Frame(parent, bg=T.CARD, highlightbackground=T.CARD_EDGE,
                    highlightthickness=1, bd=0, **kw)


def short_path(p, limit=58):
    p = str(p)
    return p if len(p) <= limit else "..." + p[-(limit - 3):]


# =============================================================================
# =============================================================================
#  MAIN APPLICATION
# =============================================================================
# =============================================================================

class SuiteApp(tk.Tk):

    STEPS = ["OEM", "DATA", "PROGRAMS", "EXECUTION"]

    def __init__(self):

        super().__init__()

        self.title("EDRC RAILWAY SIGNAL AUTOMATION SUITE")
        self.geometry("1480x940")
        self.configure(bg=T.BG)
        self.minsize(1180, 760)

        try:
            self.state("zoomed")
        except Exception:
            pass

        # ---- session state ----
        self.oem = None
        self.files = {slot["key"]: None for slot in DATA_SLOTS}
        self.selected = []            # program keys, in tick order
        self.step = 0

        self.unattended = True        # walk-away: auto Load + Start + close

        self.running = False
        self.proc = None
        self.session_dir = None
        self.results = {}
        self.claimed = set()

        self.ui_queue = queue.Queue()

        self.script_override = self._load_suite_config()

        # ---- layout ----
        self._build_header()
        self._build_body()
        self._build_footer()

        self.pages = {}
        self.page_oem = PageOEM(self.body, self)
        self.page_data = PageData(self.body, self)
        self.page_prog = PagePrograms(self.body, self)
        self.page_run = PageRun(self.body, self)

        for pg in (self.page_oem, self.page_data, self.page_prog, self.page_run):
            pg.place(x=0, y=0, relwidth=1, relheight=1)

        self.show_step(0)

        self.protocol("WM_DELETE_WINDOW", self.on_close)

        self._pump()

    # =====================================================================
    #  CHROME
    # =====================================================================

    def _build_header(self):

        head = tk.Frame(self, bg=T.INK, height=104)
        head.pack(fill="x")
        head.pack_propagate(False)

        left = tk.Frame(head, bg=T.INK)
        left.pack(side="left", padx=(24, 0))

        self._logo(left, IR_LOGO, (74, 74), "INDIAN RAILWAYS")

        title = tk.Frame(head, bg=T.INK)
        title.pack(side="left", padx=24)

        tk.Label(title, text="R A I L W A Y   S I G N A L   T E S T I N G",
                 bg=T.INK, fg=T.AMBER, font=T.f(9, "bold")
                 ).pack(anchor="w", pady=(24, 0))

        tk.Label(title, text="EDRC AUTOMATION SUITE",
                 bg=T.INK, fg=T.TEXT_INV, font=T.f(25, "bold")
                 ).pack(anchor="w")

        # OEM badge sits on the right of the title, filled once chosen.
        self.oem_badge = tk.Label(head, text="", bg=T.INK, fg=T.TEXT_MUTE,
                                  font=T.f(11, "bold"))
        self.oem_badge.pack(side="left", padx=10)

        right = tk.Frame(head, bg=T.INK)
        right.pack(side="right", padx=(0, 24))

        self._logo(right, COMPANY_LOGO, (120, 120), "EDRC TEAM")

    def _logo(self, parent, path, size, fallback):

        if PIL_OK and Path(path).exists():
            try:
                img = Image.open(path)
                img.thumbnail(size, Image.Resampling.LANCZOS)
                photo = ImageTk.PhotoImage(img)
                lab = tk.Label(parent, image=photo, bg=T.INK)
                lab.image = photo
                lab.pack(pady=8)
                return
            except Exception:
                pass

        tk.Label(parent, text=fallback, bg=T.INK, fg=T.TEXT_INV,
                 font=T.f(10, "bold")).pack(pady=30)

    def _build_body(self):

        shell = tk.Frame(self, bg=T.BG)
        shell.pack(fill="both", expand=True)

        # ---- signal mast : the step indicator ----
        mast = tk.Frame(shell, bg=T.INK, width=210)
        mast.pack(side="left", fill="y")
        mast.pack_propagate(False)

        tk.Label(mast, text="S E Q U E N C E", bg=T.INK, fg=T.TEXT_MUTE,
                 font=T.f(9, "bold")).pack(anchor="w", padx=22, pady=(26, 16))

        self.step_rows = []

        for i, name in enumerate(self.STEPS):

            row = tk.Frame(mast, bg=T.INK)
            row.pack(fill="x", padx=18, pady=7)

            lamp = Lamp(row, d=15, colour=T.GREY, bg=T.INK)
            lamp.pack(side="left")

            txt = tk.Frame(row, bg=T.INK)
            txt.pack(side="left", padx=10)

            num = tk.Label(txt, text="STEP %d" % (i + 1), bg=T.INK,
                           fg=T.TEXT_MUTE, font=T.f(8, "bold"))
            num.pack(anchor="w")

            lab = tk.Label(txt, text=name, bg=T.INK, fg=T.TEXT_MUTE,
                           font=T.f(12, "bold"))
            lab.pack(anchor="w")

            self.step_rows.append((lamp, lab, num))

            if i < len(self.STEPS) - 1:
                tk.Frame(mast, bg="#22304A", height=1).pack(
                    fill="x", padx=(26, 40))

        tk.Frame(mast, bg=T.INK).pack(fill="both", expand=True)

        self.mast_hint = tk.Label(
            mast, text="", bg=T.INK, fg=T.TEXT_MUTE,
            font=T.f(9), justify="left", wraplength=170)
        self.mast_hint.pack(anchor="w", padx=22, pady=22)

        self.body = tk.Frame(shell, bg=T.BG)
        self.body.pack(side="left", fill="both", expand=True)

    def _build_footer(self):

        foot = tk.Frame(self, bg=T.INK, height=34)
        foot.pack(fill="x")
        foot.pack_propagate(False)

        self.foot_label = tk.Label(
            foot,
            text="READY  -  SELECT AN OEM TO BEGIN",
            bg=T.INK, fg=T.TEXT_MUTE, font=T.f(9, "bold"))
        self.foot_label.pack(side="left", padx=22)

        tk.Label(foot, text="EDRC TEAM  |  ONE PROGRAM AT A TIME  |  "
                            "ONE REPORT PER PROGRAM",
                 bg=T.INK, fg="#42536E", font=T.f(9)).pack(side="right",
                                                           padx=22)

    # =====================================================================
    #  NAVIGATION
    # =====================================================================

    def show_step(self, index):

        self.step = index

        pages = [self.page_oem, self.page_data, self.page_prog, self.page_run]
        pages[index].tkraise()
        pages[index].on_show()

        hints = [
            "Pick the interlocking supplier for this yard.",
            "Load the data files once. Every program in the run uses them.",
            "Tick order is run order.",
            "Do not touch the yard terminal while a program is running.",
        ]

        self.mast_hint.config(text=hints[index])

        for i, (lamp, lab, num) in enumerate(self.step_rows):

            if i < index:
                lamp.set(T.GREEN)
                lab.config(fg="#C7D3E6")
                num.config(fg="#4C6084")
            elif i == index:
                lamp.set(T.AMBER)
                lab.config(fg=T.TEXT_INV)
                num.config(fg=T.AMBER)
            else:
                lamp.set(T.GREY, lit=False)
                lab.config(fg=T.TEXT_MUTE)
                num.config(fg="#3A4A66")

    def set_footer(self, text, colour=T.TEXT_MUTE):
        self.foot_label.config(text=text, fg=colour)

    # =====================================================================
    #  DATA FILES
    # =====================================================================

    def pick_file(self, key, label):

        path = filedialog.askopenfilename(
            title=label,
            filetypes=[("Excel Files", "*.xlsx *.xlsm *.xls"),
                       ("All Files", "*.*")])

        if not path:
            return

        self.files[key] = path
        self.page_data.refresh()
        self.set_footer("LOADED  %s  ->  %s" % (key, Path(path).name), T.GREEN)

    def clear_file(self, key):
        self.files[key] = None
        self.page_data.refresh()

    def _find_recorder(self):
        """Locates the Universal Yard Coordinate Recorder.  Looks, in order:
        a remembered path, then next to the launcher, then in the same
        folder(s) as the attached test programs (so it's found even when the
        programs live elsewhere, e.g. Desktop\\AFAT FINAL).  Falls back to a
        loose name match so a slightly different file name still works."""

        # 1. remembered choice
        saved = self.script_override.get("RECORDER")
        if saved and Path(saved).exists():
            return saved

        # 2. build the list of folders to search
        search_dirs = [SCRIPT_DIR]

        for prog in PROGRAMS:
            sp = self.script_path(prog)
            if sp:
                search_dirs.append(sp.parent)

        for k, p in self.script_override.items():
            if k != "RECORDER" and p:
                search_dirs.append(Path(p).parent)

        # de-duplicate while preserving order
        seen = set()
        folders = []
        for d in search_dirs:
            d = Path(d)
            key = str(d).lower()
            if key not in seen and d.exists():
                seen.add(key)
                folders.append(d)

        # 3. exact known names first
        for d in folders:
            for name in RECORDER_CANDIDATES:
                cand = d / name
                if cand.exists():
                    return str(cand)

        # 4. loose match - any file that looks like the recorder
        patterns = ["*coordinate*recorder*.py", "*yard*coordinate*.py",
                    "*universal*yard*.py", "*recorder*.py"]
        for d in folders:
            for pat in patterns:
                for cand in sorted(d.glob(pat)):
                    return str(cand)

        return None

    def record_new_coordinates(self):
        """LOAD COORDINATES > NEW  -  opens the Universal Yard Coordinate
        Recorder so a fresh coordinate workbook can be captured.  The recorder
        is a normal interactive tool, so it is launched directly - never
        through the walk-away helper."""

        script = self._find_recorder()

        if not script:

            messagebox.showinfo(
                "Locate the recorder",
                "Could not find universal_yard_coordinate_recorder.py next to "
                "the launcher or beside your programs.\n\nSelect it now - the "
                "location is remembered for next time.")

            script = filedialog.askopenfilename(
                title="Select universal_yard_coordinate_recorder.py",
                filetypes=[("Python", "*.py"), ("All Files", "*.*")])

            if not script:
                return

        self.script_override["RECORDER"] = script
        self._save_suite_config()

        self.set_footer("RECORDER OPEN  -  capture the yard, Export the "
                        "workbook, then use EXISTING to load it", T.AMBER)

        try:
            # Launch from the recorder's own folder, plainly (not via the
            # auto-run helper) so it behaves like opening it in PyCharm.
            subprocess.Popen([sys.executable, script],
                             cwd=str(Path(script).parent))
        except Exception as exc:
            messagebox.showerror("Recorder",
                                 "Could not start the recorder.\n\n%s" % exc)

    # =====================================================================
    #  PROGRAM SELECTION
    # =====================================================================

    def toggle_program(self, key):

        if self.running:
            return

        if key in self.selected:
            self.selected.remove(key)
        else:
            self.selected.append(key)

        self.page_prog.refresh()

    def clear_selection(self):
        self.selected = []
        self.page_prog.refresh()

    def select_all(self):
        self.selected = [p["key"] for p in PROGRAMS]
        self.page_prog.refresh()

    def script_path(self, prog):

        override = self.script_override.get(prog["key"])

        if override and Path(override).exists():
            return Path(override)

        candidate = SCRIPT_DIR / prog["script"]

        return candidate if candidate.exists() else None

    def reattach_script(self, key):
        """Point a program row at a different .py file.  Works whether or not
        a file is already attached, so a wrong attachment can be corrected."""

        prog = PROGRAM_BY_KEY[key]

        current = self.script_path(prog)

        start_dir = str(current.parent) if current else str(SCRIPT_DIR)

        path = filedialog.askopenfilename(
            title="Attach a .py file for %s" % prog["name"],
            initialdir=start_dir,
            filetypes=[("Python", "*.py"), ("All Files", "*.*")])

        if not path:
            return

        chosen = Path(path).name

        # A gentle nudge if the file name looks unrelated to this program, but
        # the choice is still honoured - names may differ.
        if chosen.lower() != prog["script"].lower():
            if not messagebox.askyesno(
                    "Attach this file?",
                    "%s normally uses:\n    %s\n\nYou picked:\n    %s\n\n"
                    "Attach it to %s anyway?"
                    % (prog["name"], prog["script"], chosen, prog["name"])):
                return

        self.script_override[key] = path
        self._save_suite_config()
        self.page_prog.refresh()

        self.set_footer("ATTACHED  %s  ->  %s" % (prog["name"], chosen),
                        T.GREEN)

    def reset_script(self, key):
        """Drop a custom attachment and go back to the default file that sits
        next to the launcher (e.g. lock_route_automation_.py)."""

        prog = PROGRAM_BY_KEY[key]

        if key not in self.script_override:
            return

        default = SCRIPT_DIR / prog["script"]

        if messagebox.askyesno(
                "Reset to default",
                "Stop using the custom file and go back to:\n\n    %s\n\n"
                "%s"
                % (prog["script"],
                   "" if default.exists()
                   else "\n(Note: that file is not in the folder yet.)")):

            self.script_override.pop(key, None)
            self._save_suite_config()
            self.page_prog.refresh()

            self.set_footer("RESET  %s  ->  default (%s)"
                            % (prog["name"], prog["script"]), T.SLATE)

    # =====================================================================
    #  EXECUTION
    # =====================================================================

    def start_run(self):

        if self.running:
            return

        if not self.selected:
            messagebox.showwarning("Nothing selected",
                                   "Tick at least one program first.")
            return

        missing = [k for k in self.selected if self.script_path(
            PROGRAM_BY_KEY[k]) is None]

        if missing:
            messagebox.showerror(
                "Script not found",
                "These programs have no script file:\n\n  %s\n\n"
                "Click the row to locate the .py file."
                % "\n  ".join(PROGRAM_BY_KEY[k]["name"] for k in missing))
            return

        # Warn about data files a program expects but which were not loaded.
        gaps = []

        for k in self.selected:
            for need in PROGRAM_BY_KEY[k]["needs"]:
                if not self.files.get(need):
                    label = next(s["label"] for s in DATA_SLOTS
                                 if s["key"] == need)
                    gaps.append("%s  needs  %s" % (PROGRAM_BY_KEY[k]["name"],
                                                   label))

        if gaps:
            proceed = messagebox.askyesno(
                "Data not loaded",
                "These files were not loaded in step 2:\n\n  %s\n\n"
                "Each program can still load its own files from its own "
                "window.\n\nStart the run anyway?" % "\n  ".join(gaps))

            if not proceed:
                return

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        self.session_dir = REPORTS_ROOT / self.oem["code"] / ("SESSION_" + stamp)
        self.session_dir.mkdir(parents=True, exist_ok=True)

        self._write_autofeed_helper()

        self.results = {}
        self.claimed = set()
        self.running = True

        self.show_step(3)
        self.page_run.begin(list(self.selected))

        self._write_session()

        threading.Thread(target=self._run_queue,
                         args=(list(self.selected),), daemon=True).start()

    def _write_autofeed_helper(self):
        """(Re)writes the auto-feed helper next to the launcher so it always
        matches this version.  Silent if it cannot be written - the run then
        falls back to launching programs directly and each program simply
        asks for its files as before."""

        global AUTOFEED_HELPER

        try:
            with open(AUTOFEED_HELPER, "w", encoding="utf-8") as fh:
                fh.write(AUTOFEED_SOURCE)
        except Exception:
            pass

    def _run_queue(self, keys):
        """Runs every selected program one after another.  The next program
        only starts after the current one has closed and its report has been
        collected."""

        self.ui(self.page_run.log, "SESSION FOLDER  %s" % self.session_dir,
                "info")
        self.ui(self.page_run.log,
                "OEM  %s  -  %d PROGRAM(S) QUEUED" % (self.oem["code"],
                                                      len(keys)), "info")

        if AUTOFEED_HELPER.exists():
            if self.unattended:
                self.ui(self.page_run.log,
                        "WALK-AWAY MODE  -  each program is loaded, started, "
                        "and closed automatically. You can leave.", "info")
            else:
                self.ui(self.page_run.log,
                        "ATTENDED MODE  -  files are pre-filled; click START "
                        "inside each program, close it to advance.", "info")

        for position, key in enumerate(keys, start=1):

            if not self.running:
                break

            prog = PROGRAM_BY_KEY[key]
            script = self.script_path(prog)

            self.ui(self.page_run.mark, key, "RUNNING")
            self.ui(self.page_run.set_progress, position - 1, len(keys))
            self.ui(self.page_run.log, "", "plain")
            self.ui(self.page_run.log,
                    "[%d/%d]  STARTING  %s" % (position, len(keys),
                                               prog["name"]), "run")
            self.ui(self.page_run.log, "        %s" % script, "dim")

            if key == "SPL_CASE_CALLING_ON":
                feed = self.files.get("SPL_CASE")
                feed_label = "SPL CASE INPUT"
            else:
                feed = self.files.get("TOC")
                feed_label = "TOC"

            if feed:
                self.ui(self.page_run.log, "        LIST    <- %s  (%s)"
                        % (Path(feed).name, feed_label), "dim")

            if self.files.get("COORDS"):
                self.ui(self.page_run.log, "        COORDS  <- %s"
                        % Path(self.files["COORDS"]).name, "dim")

            started = time.time()

            log_handle = None

            try:
                env = os.environ.copy()
                env["EDRC_OEM"] = self.oem["code"]
                env["EDRC_SESSION_DIR"] = str(self.session_dir)
                env["EDRC_PROGRAM"] = key
                env["EDRC_UNATTENDED"] = "1" if self.unattended else "0"

                # Raw slot values, kept for reference / SESSION.json.
                for slot_key, path in self.files.items():
                    if path:
                        env["EDRC_" + slot_key] = str(path)

                # What the auto-feed helper actually hands to the program:
                #   the LIST dialog gets the SPL file for SPL case, else TOC;
                #   the COORDS dialog gets the coordinates file.
                if key == "SPL_CASE_CALLING_ON":
                    list_file = self.files.get("SPL_CASE")
                else:
                    list_file = self.files.get("TOC")

                coords_file = self.files.get("COORDS")

                if list_file:
                    env["EDRC_LIST"] = str(list_file)
                else:
                    env.pop("EDRC_LIST", None)

                if coords_file:
                    env["EDRC_COORDS"] = str(coords_file)
                else:
                    env.pop("EDRC_COORDS", None)

                # Tell the helper exactly which buttons to click for THIS
                # program, by key - so a renamed / moved .py still drives.
                drv = PROGRAM_DRIVERS.get(key)
                if drv:
                    env["EDRC_DRIVE_LIST"] = drv[0]
                    env["EDRC_DRIVE_COORDS"] = drv[1]
                    env["EDRC_DRIVE_START"] = drv[2]
                else:
                    for var in ("EDRC_DRIVE_LIST", "EDRC_DRIVE_COORDS",
                                "EDRC_DRIVE_START"):
                        env.pop(var, None)

                # A per-program folder + console log, created up front so the
                # run leaves an audit trail even for an overnight session.
                prog_folder = self.session_dir / ("%02d_%s" % (position,
                                                               prog["key"]))
                prog_folder.mkdir(parents=True, exist_ok=True)

                try:
                    log_handle = open(prog_folder / "console.log", "w",
                                      encoding="utf-8")
                except Exception:
                    log_handle = None

                self.proc = subprocess.Popen(
                    [sys.executable, str(AUTOFEED_HELPER), str(script)],
                    cwd=str(SCRIPT_DIR), env=env,
                    stdout=log_handle, stderr=subprocess.STDOUT)

                code = self.proc.wait()

            except Exception as exc:

                self.ui(self.page_run.log, "        LAUNCH FAILED  %s" % exc,
                        "fail")
                self.ui(self.page_run.mark, key, "FAILED")
                self.results[key] = {"status": "FAILED", "error": str(exc)}
                continue

            finally:
                self.proc = None
                if log_handle is not None:
                    try:
                        log_handle.close()
                    except Exception:
                        pass

            elapsed = int(time.time() - started)

            reports = self._collect_reports(prog, position, started)

            if not self.running:
                self.ui(self.page_run.mark, key, "STOPPED")
                self.results[key] = {"status": "STOPPED", "reports": reports}
                self.ui(self.page_run.log, "        STOPPED BY OPERATOR",
                        "fail")
                break

            if reports:
                for rep in reports:
                    self.ui(self.page_run.log, "        REPORT  %s"
                            % Path(rep).name, "ok")
                status = "COMPLETE"
            else:
                self.ui(self.page_run.log,
                        "        NO NEW REPORT FOUND FOR THIS PROGRAM", "warn")
                status = "NO REPORT"

            self.ui(self.page_run.log,
                    "        FINISHED  %s  (exit %s, %dm %02ds)"
                    % (prog["name"], code, elapsed // 60, elapsed % 60), "ok")

            self.ui(self.page_run.mark, key, status)

            self.results[key] = {
                "status": status,
                "exit_code": code,
                "seconds": elapsed,
                "reports": reports,
            }

            self.ui(self.page_run.set_progress, position, len(keys))

        self.running = False
        self._write_session()

        self.ui(self.page_run.finish)

    def _collect_reports(self, prog, position, since):
        """Copies any Excel report the program produced into the session
        folder.  Files are matched by the program's own report prefixes, and
        anything newer than the launch time is taken as a fallback."""

        folder = self.session_dir / ("%02d_%s" % (position, prog["key"]))

        found = []
        prefixes = [p.lower() for p in prog["reports"]]

        inputs = {str(Path(p).resolve()).lower()
                  for p in self.files.values() if p}

        try:
            candidates = list(SCRIPT_DIR.glob("*.xlsx"))
        except Exception:
            return found

        fresh = []

        for path in candidates:

            try:
                resolved = str(path.resolve()).lower()

                # Never pick up a data file, and never pick up a report that
                # an earlier program in this session already claimed.
                if resolved in inputs or resolved in self.claimed:
                    continue

                if path.stat().st_mtime < since - 2:
                    continue

                fresh.append(path)

            except Exception:
                continue

        # Prefer files whose name matches this program's own report prefix.
        # If the program was renamed, fall back to any unclaimed new file so
        # a report is collected rather than lost.
        matched = [p for p in fresh
                   if any(p.name.lower().startswith(pref) for pref in prefixes)]

        for path in (matched or fresh):

            try:
                folder.mkdir(parents=True, exist_ok=True)

                target = folder / path.name
                shutil.copy2(path, target)

                self.claimed.add(str(path.resolve()).lower())
                found.append(str(target))

            except Exception:
                continue

        return found

    def stop_run(self):

        if not self.running:
            return

        if not messagebox.askyesno(
                "Stop the run",
                "Stop after closing the program that is running now?\n\n"
                "The remaining programs in the queue will not start."):
            return

        self.running = False

        self.page_run.log("STOP REQUESTED BY OPERATOR", "fail")

        if self.proc and self.proc.poll() is None:
            try:
                self.proc.terminate()
            except Exception:
                pass

    def open_session_folder(self):

        if not self.session_dir or not Path(self.session_dir).exists():
            messagebox.showinfo("Reports", "No session folder yet.")
            return

        try:
            os.startfile(str(self.session_dir))
        except AttributeError:
            subprocess.Popen(["xdg-open", str(self.session_dir)])
        except Exception as exc:
            messagebox.showerror("Reports", str(exc))

    # =====================================================================
    #  PERSISTENCE
    # =====================================================================

    def _write_session(self):

        if not self.session_dir:
            return

        payload = {
            "oem": self.oem["code"] if self.oem else None,
            "created": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "data_files": {k: v for k, v in self.files.items() if v},
            "run_order": [PROGRAM_BY_KEY[k]["name"] for k in self.selected],
            "results": self.results,
        }

        try:
            with open(self.session_dir / "SESSION.json", "w",
                      encoding="utf-8") as fh:
                json.dump(payload, fh, indent=2)
        except Exception:
            pass

    def _load_suite_config(self):

        try:
            if SUITE_CONFIG.exists():
                with open(SUITE_CONFIG, "r", encoding="utf-8") as fh:
                    return json.load(fh)
        except Exception:
            pass

        return {}

    def _save_suite_config(self):

        try:
            with open(SUITE_CONFIG, "w", encoding="utf-8") as fh:
                json.dump(self.script_override, fh, indent=2)
        except Exception:
            pass

    # =====================================================================
    #  THREAD SAFE UI
    # =====================================================================

    def ui(self, fn, *args):
        """Marshals a call from the runner thread onto the tk main loop.

        Tk is not thread safe and calling after() straight from a worker
        thread is unreliable, so the call is parked on a queue that the
        main loop drains in _pump()."""

        self.ui_queue.put((fn, args))

    def _pump(self):
        """Drains anything the runner thread posted, then re-arms itself."""

        while True:
            try:
                fn, args = self.ui_queue.get_nowait()
            except queue.Empty:
                break

            try:
                fn(*args)
            except Exception as exc:
                print("UI update failed:", exc)

        self.after(60, self._pump)

    def on_close(self):

        if self.running:
            if not messagebox.askyesno(
                    "Run in progress",
                    "A program is still running. Close the suite anyway?"):
                return
            self.running = False

        self.destroy()


# =============================================================================
# =============================================================================
#  STEP 1  -  OEM
# =============================================================================
# =============================================================================

class PageOEM(tk.Frame):

    def __init__(self, parent, app):

        super().__init__(parent, bg=T.BG)
        self.app = app

        head = tk.Frame(self, bg=T.BG)
        head.pack(fill="x", padx=40, pady=(34, 6))

        tk.Label(head, text="S T E P   0 1", bg=T.BG, fg=T.BLUE,
                 font=T.f(9, "bold")).pack(anchor="w")

        tk.Label(head, text="Select the interlocking OEM", bg=T.BG,
                 fg=T.TEXT, font=T.f(24, "bold")).pack(anchor="w", pady=(4, 2))

        tk.Label(head,
                 text="The OEM decides how the yard terminal behaves and where "
                      "this session's reports are filed.",
                 bg=T.BG, fg=T.TEXT_SOFT, font=T.f(11)).pack(anchor="w")

        grid = tk.Frame(self, bg=T.BG)
        grid.pack(fill="both", expand=True, padx=40, pady=26)

        for c in range(3):
            grid.columnconfigure(c, weight=1, uniform="oem")
        for r in range(2):
            grid.rowconfigure(r, weight=1, uniform="oem")

        for i, oem in enumerate(OEMS):
            self._card(grid, oem).grid(row=i // 3, column=i % 3,
                                       padx=12, pady=12, sticky="nsew")

    def _card(self, parent, oem):

        holder = tk.Frame(parent, bg=T.CARD, highlightthickness=1,
                          highlightbackground=T.CARD_EDGE, cursor="hand2")

        stripe = tk.Frame(holder, bg=oem["accent"], height=6)
        stripe.pack(fill="x")

        inner = tk.Frame(holder, bg=T.CARD)
        inner.pack(fill="both", expand=True, padx=26, pady=22)

        lamp = Lamp(inner, d=13, colour=oem["accent"], bg=T.CARD)
        lamp.pack(anchor="w")

        name = tk.Label(inner, text=oem["code"], bg=T.CARD, fg=T.TEXT,
                        font=T.f(22, "bold"))
        name.pack(anchor="w", pady=(14, 0))

        note = tk.Label(inner, text=oem["note"], bg=T.CARD, fg=T.TEXT_SOFT,
                        font=T.f(11))
        note.pack(anchor="w", pady=(2, 0))

        tk.Frame(inner, bg=T.CARD).pack(fill="both", expand=True)

        go = tk.Label(inner, text="OPEN  >", bg=T.CARD, fg=oem["accent"],
                      font=T.f(10, "bold"))
        go.pack(anchor="w")

        widgets = [holder, inner, lamp, name, note, go, stripe]

        def enter(_=None):
            holder.config(highlightbackground=oem["accent"],
                          highlightthickness=2)
            go.config(text="OPEN  >>")

        def leave(_=None):
            holder.config(highlightbackground=T.CARD_EDGE,
                          highlightthickness=1)
            go.config(text="OPEN  >")

        def choose(_=None):
            self.app.oem = oem
            self.app.oem_badge.config(
                text="  //  %s" % oem["code"], fg=oem["accent"])
            self.app.set_footer("OEM  %s  SELECTED" % oem["code"],
                                oem["accent"])
            self.app.show_step(1)

        for w in widgets:
            w.bind("<Enter>", enter)
            w.bind("<Leave>", leave)
            w.bind("<Button-1>", choose)
            try:
                w.config(cursor="hand2")
            except Exception:
                pass

        return holder

    def on_show(self):
        self.app.set_footer("READY  -  SELECT AN OEM TO BEGIN")


# =============================================================================
# =============================================================================
#  STEP 2  -  DATA
# =============================================================================
# =============================================================================

class PageData(tk.Frame):

    def __init__(self, parent, app):

        super().__init__(parent, bg=T.BG)
        self.app = app
        self.rows = {}

        head = tk.Frame(self, bg=T.BG)
        head.pack(fill="x", padx=40, pady=(30, 6))

        tk.Label(head, text="S T E P   0 2", bg=T.BG, fg=T.BLUE,
                 font=T.f(9, "bold")).pack(anchor="w")

        self.title_lab = tk.Label(head, text="Load the yard data", bg=T.BG,
                                  fg=T.TEXT, font=T.f(24, "bold"))
        self.title_lab.pack(anchor="w", pady=(4, 2))

        tk.Label(head,
                 text="Load each file once here and every program in the run "
                      "receives it.",
                 bg=T.BG, fg=T.TEXT_SOFT, font=T.f(11)).pack(anchor="w")

        # ---- scrollable list of data slots ----
        body = tk.Frame(self, bg=T.BG)
        body.pack(fill="both", expand=True, padx=40, pady=(20, 6))

        canvas = tk.Canvas(body, bg=T.BG, highlightthickness=0, bd=0)
        scroll = tk.Scrollbar(body, orient="vertical", command=canvas.yview)
        holder = tk.Frame(canvas, bg=T.BG)

        holder.bind("<Configure>", lambda e: canvas.configure(
            scrollregion=canvas.bbox("all")))

        window = canvas.create_window((0, 0), window=holder, anchor="nw")
        canvas.bind("<Configure>",
                    lambda e: canvas.itemconfig(window, width=e.width))
        canvas.configure(yscrollcommand=scroll.set)

        canvas.pack(side="left", fill="both", expand=True)
        scroll.pack(side="right", fill="y")

        canvas.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(
            int(-e.delta / 120), "units") if self.winfo_ismapped() else None)

        for slot in DATA_SLOTS:
            self._slot_row(holder, slot)

        # ---- footer nav ----
        nav = tk.Frame(self, bg=T.BG)
        nav.pack(fill="x", padx=40, pady=(6, 26))

        GhostButton(nav, "<  BACK", lambda: self.app.show_step(0),
                    w=150).pack(side="left")

        self.ready_lab = tk.Label(nav, text="", bg=T.BG, fg=T.TEXT_SOFT,
                                  font=T.f(10, "bold"))
        self.ready_lab.pack(side="left", padx=18)

        RButton(nav, "NEXT  >", lambda: self.app.show_step(2),
                w=190, face=T.BLUE).pack(side="right")

    # ------------------------------------------------------------------

    def _slot_row(self, parent, slot):

        row = card(parent)
        row.pack(fill="x", pady=7)

        inner = tk.Frame(row, bg=T.CARD)
        inner.pack(fill="x", padx=22, pady=16)

        # left : lamp + text
        left = tk.Frame(inner, bg=T.CARD)
        left.pack(side="left", fill="x", expand=True)

        top = tk.Frame(left, bg=T.CARD)
        top.pack(anchor="w")

        lamp = Lamp(top, d=13, colour=T.GREY, bg=T.CARD)
        lamp.pack(side="left", pady=(1, 0))

        tk.Label(top, text=slot["label"], bg=T.CARD, fg=T.TEXT,
                 font=T.f(13, "bold")).pack(side="left", padx=8)

        tk.Label(left, text=slot["hint"], bg=T.CARD, fg=T.TEXT_SOFT,
                 font=T.f(10), justify="left", wraplength=620).pack(
                     anchor="w", pady=(4, 0))

        status = tk.Label(left, text="Not loaded", bg=T.CARD, fg=T.TEXT_SOFT,
                          font=T.mono(9))
        status.pack(anchor="w", pady=(6, 0))

        # right : action buttons
        right = tk.Frame(inner, bg=T.CARD)
        right.pack(side="right")

        if slot["recorder"]:

            pair = tk.Frame(right, bg=T.CARD)
            pair.pack(side="left")

            RButton(pair, "NEW", self.app.record_new_coordinates,
                    w=104, h=42, face=T.VIOLET, bg=T.CARD,
                    font=T.f(10, "bold")).pack(side="left", padx=(0, 8))

            RButton(pair, "EXISTING",
                    lambda k=slot["key"], l=slot["label"]:
                        self.app.pick_file(k, l),
                    w=124, h=42, face=T.BLUE, bg=T.CARD,
                    font=T.f(10, "bold")).pack(side="left")

        else:

            RButton(right, "BROWSE",
                    lambda k=slot["key"], l=slot["label"]:
                        self.app.pick_file(k, l),
                    w=140, h=42, face=T.BLUE, bg=T.CARD,
                    font=T.f(10, "bold")).pack(side="left")

        clear = GhostButton(right, "CLEAR",
                            lambda k=slot["key"]: self.app.clear_file(k),
                            w=96, h=42, colour=T.TEXT_SOFT)
        clear.configure(bg=T.CARD)
        clear.itemconfig(clear.shape, fill=T.CARD)
        clear.base_bg = T.CARD
        clear.pack(side="left", padx=(8, 0))

        self.rows[slot["key"]] = (lamp, status)

    # ------------------------------------------------------------------

    def refresh(self):

        for slot in DATA_SLOTS:

            lamp, status = self.rows[slot["key"]]
            path = self.app.files.get(slot["key"])

            if path:
                lamp.set(T.GREEN)
                status.config(text=short_path(path), fg=T.GREEN)
            else:
                lamp.set(T.GREY, lit=False)
                status.config(text="Not loaded", fg=T.TEXT_SOFT)

        loaded = []

        if self.app.files.get("TOC"):
            loaded.append("TOC")
        if self.app.files.get("COORDS"):
            loaded.append("coordinates")
        if self.app.files.get("SPL_CASE"):
            loaded.append("SPL case")

        if not self.app.files.get("TOC"):
            self.ready_lab.config(text="Load the TOC to run any program",
                                  fg=T.TEXT_SOFT)
        else:
            self.ready_lab.config(
                text="Loaded: " + ", ".join(loaded),
                fg=T.GREEN)

    def on_show(self):

        if self.app.oem:
            self.title_lab.config(
                text="Load the yard data  -  %s" % self.app.oem["code"])

        self.refresh()
        self.app.set_footer("STEP 2  -  LOAD THE DATA FILES")


# =============================================================================
# =============================================================================
#  STEP 3  -  PROGRAMS
# =============================================================================
# =============================================================================

class PagePrograms(tk.Frame):

    def __init__(self, parent, app):

        super().__init__(parent, bg=T.BG)
        self.app = app
        self.rows = {}

        head = tk.Frame(self, bg=T.BG)
        head.pack(fill="x", padx=40, pady=(30, 6))

        tk.Label(head, text="S T E P   0 3", bg=T.BG, fg=T.BLUE,
                 font=T.f(9, "bold")).pack(anchor="w")

        tk.Label(head, text="Choose the programs to run", bg=T.BG, fg=T.TEXT,
                 font=T.f(24, "bold")).pack(anchor="w", pady=(4, 2))

        tk.Label(head,
                 text="Tick order is run order. Tick SIGNAL CLEARANCE then SPL "
                      "CASE CALLING ON and clearance runs first, writes its "
                      "report, and only then does calling-on start.",
                 bg=T.BG, fg=T.TEXT_SOFT, font=T.f(11),
                 justify="left", wraplength=900).pack(anchor="w")

        # ---- run order strip ----
        strip = card(self)
        strip.pack(fill="x", padx=40, pady=(18, 4))

        inner = tk.Frame(strip, bg=T.CARD)
        inner.pack(fill="x", padx=20, pady=12)

        tk.Label(inner, text="RUN ORDER", bg=T.CARD, fg=T.TEXT_SOFT,
                 font=T.f(9, "bold")).pack(side="left")

        self.order_lab = tk.Label(inner, text="nothing selected", bg=T.CARD,
                                  fg=T.TEXT_SOFT, font=T.f(11, "bold"))
        self.order_lab.pack(side="left", padx=14)

        GhostButton(inner, "CLEAR", self.app.clear_selection, w=92, h=34,
                    colour=T.TEXT_SOFT).pack(side="right")

        sel_all = GhostButton(inner, "SELECT ALL", self.app.select_all,
                              w=124, h=34, colour=T.BLUE)
        sel_all.pack(side="right", padx=8)

        for b in (sel_all,):
            b.configure(bg=T.CARD)
            b.itemconfig(b.shape, fill=T.CARD)
            b.base_bg = T.CARD

        # ---- program list ----
        body = tk.Frame(self, bg=T.BG)
        body.pack(fill="both", expand=True, padx=40, pady=(10, 6))

        canvas = tk.Canvas(body, bg=T.BG, highlightthickness=0, bd=0)
        scroll = tk.Scrollbar(body, orient="vertical", command=canvas.yview)
        holder = tk.Frame(canvas, bg=T.BG)

        holder.bind("<Configure>", lambda e: canvas.configure(
            scrollregion=canvas.bbox("all")))

        window = canvas.create_window((0, 0), window=holder, anchor="nw")
        canvas.bind("<Configure>",
                    lambda e: canvas.itemconfig(window, width=e.width))
        canvas.configure(yscrollcommand=scroll.set)

        canvas.pack(side="left", fill="both", expand=True)
        scroll.pack(side="right", fill="y")

        for prog in PROGRAMS:
            self._program_row(holder, prog)

        # ---- nav ----
        nav = tk.Frame(self, bg=T.BG)
        nav.pack(fill="x", padx=40, pady=(6, 26))

        GhostButton(nav, "<  BACK", lambda: self.app.show_step(1),
                    w=150).pack(side="left")

        # walk-away toggle
        toggle_wrap = tk.Frame(nav, bg=T.BG)
        toggle_wrap.pack(side="left", padx=26)

        self.toggle = Toggle(toggle_wrap, value=self.app.unattended,
                             command=self._set_unattended, bg=T.BG)
        self.toggle.pack(side="left")

        text_wrap = tk.Frame(toggle_wrap, bg=T.BG)
        text_wrap.pack(side="left", padx=10)

        tk.Label(text_wrap, text="WALK-AWAY MODE", bg=T.BG, fg=T.TEXT,
                 font=T.f(11, "bold")).pack(anchor="w")

        self.toggle_hint = tk.Label(
            text_wrap,
            text="Loads, starts and closes each program for you",
            bg=T.BG, fg=T.TEXT_SOFT, font=T.f(9))
        self.toggle_hint.pack(anchor="w")

        self.start_btn = RButton(nav, "START AUTOMATION", self.app.start_run,
                                 w=246, h=50, face=T.GREEN,
                                 font=T.f(12, "bold"))
        self.start_btn.pack(side="right")

    def _set_unattended(self, value):

        self.app.unattended = value

        if value:
            self.toggle_hint.config(
                text="Loads, starts and closes each program for you")
        else:
            self.toggle_hint.config(
                text="Files pre-filled; you click Start in each program")

    # ------------------------------------------------------------------

    def _program_row(self, parent, prog):

        row = card(parent)
        row.pack(fill="x", pady=7)

        inner = tk.Frame(row, bg=T.CARD)
        inner.pack(fill="x", padx=20, pady=16)

        check = CheckMark(inner, bg=T.CARD)
        check.pack(side="left", padx=(0, 16))

        left = tk.Frame(inner, bg=T.CARD)
        left.pack(side="left", fill="x", expand=True)

        name = tk.Label(left, text=prog["name"], bg=T.CARD, fg=T.TEXT,
                        font=T.f(14, "bold"))
        name.pack(anchor="w")

        desc = tk.Label(left, text=prog["desc"], bg=T.CARD, fg=T.TEXT_SOFT,
                        font=T.f(10), justify="left", wraplength=760)
        desc.pack(anchor="w", pady=(3, 0))

        meta = tk.Label(left, text="", bg=T.CARD, fg=T.TEXT_SOFT,
                        font=T.mono(9))
        meta.pack(anchor="w", pady=(6, 0))

        right = tk.Frame(inner, bg=T.CARD)
        right.pack(side="right")

        state = tk.Label(right, text="", bg=T.CARD, fg=T.TEXT_SOFT,
                         font=T.f(10, "bold"))
        state.pack(anchor="e")

        # File controls - these do NOT tick the program, they only change or
        # reset which .py file this row points at.
        file_btns = tk.Frame(right, bg=T.CARD)
        file_btns.pack(anchor="e", pady=(8, 0))

        change_btn = GhostButton(
            file_btns, "CHANGE FILE",
            lambda k=prog["key"]: self.app.reattach_script(k),
            w=118, h=32, colour=T.BLUE)
        change_btn.configure(bg=T.CARD)
        change_btn.itemconfig(change_btn.shape, fill=T.CARD)
        change_btn.base_bg = T.CARD
        change_btn.pack(side="left")

        reset_btn = GhostButton(
            file_btns, "RESET",
            lambda k=prog["key"]: self.app.reset_script(k),
            w=78, h=32, colour=T.TEXT_SOFT)
        reset_btn.configure(bg=T.CARD)
        reset_btn.itemconfig(reset_btn.shape, fill=T.CARD)
        reset_btn.base_bg = T.CARD
        reset_btn.pack(side="left", padx=(8, 0))

        clickable = [row, inner, left, name, desc, check]

        def toggle(_=None):
            if self.app.script_path(prog) is None:
                self.app.reattach_script(prog["key"])
            else:
                self.app.toggle_program(prog["key"])

        def enter(_=None):
            row.config(highlightbackground=T.CARD_EDGE_HOT)

        def leave(_=None):
            selected = prog["key"] in self.app.selected
            row.config(highlightbackground=T.BLUE if selected else T.CARD_EDGE)

        for w in clickable:
            w.bind("<Button-1>", toggle)
            w.bind("<Enter>", enter)
            w.bind("<Leave>", leave)
            try:
                w.config(cursor="hand2")
            except Exception:
                pass

        self.rows[prog["key"]] = {
            "frame": row, "check": check, "meta": meta, "state": state,
            "reset": reset_btn,
        }

    # ------------------------------------------------------------------

    def refresh(self):

        for prog in PROGRAMS:

            ref = self.rows[prog["key"]]
            selected = prog["key"] in self.app.selected

            order = (self.app.selected.index(prog["key"]) + 1
                     if selected else None)

            ref["check"].set(selected, order)

            ref["frame"].config(
                highlightbackground=T.BLUE if selected else T.CARD_EDGE,
                highlightthickness=2 if selected else 1)

            script = self.app.script_path(prog)
            override = self.app.script_override.get(prog["key"])
            has_override = bool(override and Path(override).exists())

            # RESET only means something when a custom file is attached.
            ref["reset"].set_enabled(has_override)

            if script is None:
                ref["meta"].config(
                    text="NO FILE ATTACHED  -  looked for %s  -  click the "
                         "row or CHANGE FILE to attach the .py" % prog["script"],
                    fg=T.RED)
                ref["state"].config(text="MISSING", fg=T.RED)
                continue

            needs = []

            for key in prog["needs"]:
                label = next(s["label"] for s in DATA_SLOTS
                             if s["key"] == key)
                mark = "OK" if self.app.files.get(key) else "--"
                needs.append("%s %s" % (mark, label.replace("LOAD ", "")
                                        .replace("UPLOAD ", "")))

            if has_override:
                attached = "custom: %s" % short_path(override, 46)
            else:
                attached = prog["script"]

            ref["meta"].config(text=attached + "   |   " +
                                    "   ".join(needs), fg=T.TEXT_SOFT)

            if selected:
                ref["state"].config(text="RUN #%d" % order, fg=T.BLUE)
            elif has_override:
                ref["state"].config(text="CUSTOM", fg=T.VIOLET)
            else:
                ref["state"].config(text="", fg=T.TEXT_SOFT)

        if self.app.selected:
            names = [PROGRAM_BY_KEY[k]["name"] for k in self.app.selected]
            self.order_lab.config(
                text="   >   ".join("%d. %s" % (i + 1, n)
                                    for i, n in enumerate(names)),
                fg=T.TEXT)
            self.start_btn.set_enabled(True)
        else:
            self.order_lab.config(text="nothing selected", fg=T.TEXT_SOFT)
            self.start_btn.set_enabled(False)

    def on_show(self):
        self.refresh()
        self.app.set_footer("STEP 3  -  TICK THE PROGRAMS IN THE ORDER YOU "
                            "WANT THEM TO RUN")


# =============================================================================
# =============================================================================
#  STEP 4  -  EXECUTION
# =============================================================================
# =============================================================================

class PageRun(tk.Frame):

    def __init__(self, parent, app):

        super().__init__(parent, bg=T.BG)
        self.app = app
        self.queue_rows = {}

        head = tk.Frame(self, bg=T.BG)
        head.pack(fill="x", padx=40, pady=(30, 6))

        tk.Label(head, text="S T E P   0 4", bg=T.BG, fg=T.BLUE,
                 font=T.f(9, "bold")).pack(anchor="w")

        tk.Label(head, text="Execution", bg=T.BG, fg=T.TEXT,
                 font=T.f(24, "bold")).pack(anchor="w", pady=(4, 2))

        tk.Label(head,
                 text="In walk-away mode each program is loaded, started and "
                      "closed for you. Leave it running - the queue advances "
                      "on its own.",
                 bg=T.BG, fg=T.TEXT_SOFT, font=T.f(11),
                 justify="left", wraplength=900).pack(anchor="w")

        # ---- progress bar ----
        bar_holder = tk.Frame(self, bg=T.BG)
        bar_holder.pack(fill="x", padx=40, pady=(18, 0))

        self.bar = tk.Canvas(bar_holder, height=10, bg=T.BG,
                             highlightthickness=0, bd=0)
        self.bar.pack(fill="x")

        self.bar_bg = self.bar.create_rectangle(0, 0, 10, 10, fill="#D9E0EB",
                                                outline="#D9E0EB")
        self.bar_fg = self.bar.create_rectangle(0, 0, 0, 10, fill=T.GREEN,
                                                outline=T.GREEN)

        self.bar.bind("<Configure>", self._resize_bar)

        self.progress_lab = tk.Label(bar_holder, text="", bg=T.BG,
                                     fg=T.TEXT_SOFT, font=T.f(10, "bold"))
        self.progress_lab.pack(anchor="w", pady=(6, 0))

        # ---- split : queue | console ----
        split = tk.Frame(self, bg=T.BG)
        split.pack(fill="both", expand=True, padx=40, pady=(12, 6))

        queue_card = card(split)
        queue_card.pack(side="left", fill="both", expand=True, padx=(0, 12))

        tk.Label(queue_card, text="QUEUE", bg=T.CARD, fg=T.TEXT_SOFT,
                 font=T.f(9, "bold")).pack(anchor="w", padx=18, pady=(14, 6))

        self.queue_holder = tk.Frame(queue_card, bg=T.CARD)
        self.queue_holder.pack(fill="both", expand=True, padx=10, pady=(0, 12))

        log_card = card(split)
        log_card.pack(side="left", fill="both", expand=True)

        tk.Label(log_card, text="LIVE LOG", bg=T.CARD, fg=T.TEXT_SOFT,
                 font=T.f(9, "bold")).pack(anchor="w", padx=18, pady=(14, 6))

        log_wrap = tk.Frame(log_card, bg=T.INK)
        log_wrap.pack(fill="both", expand=True, padx=14, pady=(0, 14))

        self.log_text = tk.Text(log_wrap, bg=T.INK, fg="#C9D6EA",
                                font=T.mono(10), relief="flat", bd=0,
                                padx=12, pady=10, wrap="word")
        self.log_text.pack(fill="both", expand=True)

        self.log_text.tag_config("info", foreground="#8FA0BC")
        self.log_text.tag_config("dim", foreground="#5C6E8C")
        self.log_text.tag_config("run", foreground=T.AMBER)
        self.log_text.tag_config("ok", foreground="#4ADE80")
        self.log_text.tag_config("warn", foreground=T.AMBER)
        self.log_text.tag_config("fail", foreground="#FF8177")
        self.log_text.tag_config("plain", foreground="#C9D6EA")

        self.log_text.config(state="disabled")

        # ---- nav ----
        nav = tk.Frame(self, bg=T.BG)
        nav.pack(fill="x", padx=40, pady=(6, 26))

        self.back_btn = GhostButton(nav, "<  BACK",
                                    lambda: self.app.show_step(2), w=150)
        self.back_btn.pack(side="left")

        self.stop_btn = RButton(nav, "STOP", self.app.stop_run, w=160, h=50,
                                face=T.RED, font=T.f(12, "bold"))
        self.stop_btn.pack(side="right")

        self.reports_btn = RButton(nav, "OPEN REPORTS FOLDER",
                                   self.app.open_session_folder, w=248, h=50,
                                   face=T.SLATE, font=T.f(11, "bold"))
        self.reports_btn.pack(side="right", padx=10)

    # ------------------------------------------------------------------

    def _resize_bar(self, event):

        self.bar.coords(self.bar_bg, 0, 0, event.width, 10)
        self._bar_width = event.width
        self._draw_bar()

    def _draw_bar(self):

        width = getattr(self, "_bar_width", 400)
        done = getattr(self, "_done", 0)
        total = max(1, getattr(self, "_total", 1))

        self.bar.coords(self.bar_fg, 0, 0, width * (done / total), 10)

    def set_progress(self, done, total):

        self._done, self._total = done, total
        self._draw_bar()

        self.progress_lab.config(
            text="%d of %d programs complete" % (done, total),
            fg=T.GREEN if done == total else T.TEXT_SOFT)

    # ------------------------------------------------------------------

    def begin(self, keys):

        for child in self.queue_holder.winfo_children():
            child.destroy()

        self.queue_rows = {}

        self.log_text.config(state="normal")
        self.log_text.delete("1.0", "end")
        self.log_text.config(state="disabled")

        for i, key in enumerate(keys, start=1):

            prog = PROGRAM_BY_KEY[key]

            row = tk.Frame(self.queue_holder, bg=T.CARD)
            row.pack(fill="x", padx=8, pady=5)

            lamp = Lamp(row, d=15, colour=T.GREY, bg=T.CARD)
            lamp.pack(side="left", padx=(4, 10))

            text = tk.Frame(row, bg=T.CARD)
            text.pack(side="left", fill="x", expand=True)

            tk.Label(text, text="%02d   %s" % (i, prog["name"]), bg=T.CARD,
                     fg=T.TEXT, font=T.f(12, "bold")).pack(anchor="w")

            state = tk.Label(text, text="WAITING", bg=T.CARD, fg=T.TEXT_SOFT,
                             font=T.mono(9))
            state.pack(anchor="w")

            self.queue_rows[key] = (lamp, state)

        self.set_progress(0, len(keys))
        self.stop_btn.set_enabled(True)
        self.back_btn.set_enabled(False)

        self.app.set_footer("RUN IN PROGRESS  -  DO NOT USE THE YARD TERMINAL",
                            T.AMBER)

    def mark(self, key, status):

        if key not in self.queue_rows:
            return

        lamp, state = self.queue_rows[key]

        colours = {
            "WAITING": (T.GREY, T.TEXT_SOFT),
            "RUNNING": (T.AMBER, T.AMBER),
            "COMPLETE": (T.GREEN, T.GREEN),
            "NO REPORT": (T.AMBER, T.AMBER),
            "STOPPED": (T.RED, T.RED),
            "FAILED": (T.RED, T.RED),
        }

        lamp_colour, text_colour = colours.get(status, (T.GREY, T.TEXT_SOFT))

        lamp.set(lamp_colour, lit=status != "WAITING")
        state.config(text=status, fg=text_colour)

    def log(self, message, tag="plain"):

        stamp = datetime.now().strftime("%H:%M:%S")
        line = ("%s  %s\n" % (stamp, message)) if message else "\n"

        self.log_text.config(state="normal")
        self.log_text.insert("end", line, tag)
        self.log_text.see("end")
        self.log_text.config(state="disabled")

    def finish(self):

        self.stop_btn.set_enabled(False)
        self.back_btn.set_enabled(True)

        done = sum(1 for r in self.app.results.values()
                   if r.get("status") == "COMPLETE")

        self.log("", "plain")
        self.log("SESSION FINISHED  -  %d COMPLETE, %d TOTAL"
                 % (done, len(self.app.results)), "ok")
        self.log("REPORTS  %s" % self.app.session_dir, "info")

        self.app.set_footer("SESSION FINISHED  -  REPORTS FILED IN %s"
                            % self.app.session_dir, T.GREEN)

        if self.app.session_dir and Path(self.app.session_dir).exists():
            try:
                os.startfile(str(self.app.session_dir))
            except Exception:
                pass

    def on_show(self):
        pass


# =============================================================================
# =============================================================================
#  RUN
# =============================================================================
# =============================================================================

if __name__ == "__main__":

    REPORTS_ROOT.mkdir(parents=True, exist_ok=True)

    app = SuiteApp()
    app.mainloop()
